# Generated by Django 6.1 on 2026-08-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_batch_status_alter_distribution_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('L', 'Litre (L)'), ('ml', 'Millilitre (ml)')], default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('L', 'Litre (L)'), ('ml', 'Millilitre (ml)')], default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='package_unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('L', 'Litre (L)'), ('ml', 'Millilitre (ml)')], default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('L', 'Litre (L)'), ('ml', 'Millilitre (ml)')], default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='qualitycheck',
            name='quality_grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=20),
        ),
    ]
