# Generated by Django 6.1 on 2026-08-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_batch_unit_alter_delivery_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packaging',
            name='package_unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('L', 'Litre (L)'), ('ml', 'Millilitre (ml)'), ('pcs', 'Pieces')], default='kg', max_length=20),
        ),
    ]
